name: Publish to pypi
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

    paths:
      - "stremio/__init__.py"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build stremio
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools wheel twine build
          python -m build -n --sdist

      - name: Upload to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
